# Generated by Django 6.0.7 on 2026-07-20 16:06

import django.db.models.deletion
import django.utils.timezone
import siifweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_reporte', models.CharField(choices=[('cdp', 'Consolidado de disponibilidades'), ('compromisos', 'Consolidado de compromisos'), ('obligaciones', 'Consolidado de obligaciones'), ('reservas', 'Consolidado de reservas'), ('historial', 'Historial de orden de gasto 2 (rango completo)')], max_length=20, verbose_name='Tipo de reporte')),
                ('archivo', models.FileField(upload_to='reportes/', verbose_name='Archivo')),
                ('fecha_descarga', models.DateField(default=django.utils.timezone.localdate, help_text='Los saldos del reporte son la foto de este dia', verbose_name='Fecha de descarga')),
                ('vigencia', models.IntegerField(blank=True, choices=siifweb.models.listado_vigencias, help_text='Dejar vacia en el historial de ordenes de gasto 2: se descarga por rango completo, no por vigencia', null=True, verbose_name='Vigencia')),
                ('filas', models.IntegerField(default=0, verbose_name='Numero de filas')),
                ('hash', models.CharField(blank=True, help_text='Detecta recargas del mismo archivo', max_length=64, unique=True, verbose_name='Hash del archivo')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('OK', 'Procesado'), ('E', 'Con error')], default='P', max_length=2, verbose_name='Estado')),
                ('mensaje', models.TextField(blank=True, verbose_name='Resultado del proceso')),
            ],
            options={
                'verbose_name': 'Carga del reporte',
                'verbose_name_plural': 'Cargas del reporte',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
            },
        ),
        migrations.CreateModel(
            name='OrdenGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de orden de gasto',
                'verbose_name_plural': 'Tipos de orden de gasto',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vigencia', models.IntegerField(choices=siifweb.models.listado_vigencias, verbose_name='Vigencia de constitucion')),
                ('nro_reserva', models.CharField(max_length=20, verbose_name='Numero')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de reserva')),
                ('objeto_reserva', models.TextField(blank=True, verbose_name='Objeto de la reserva')),
                ('acto_admon', models.TextField(blank=True, verbose_name='Acto administrativo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Codigo')),
                ('nombre', models.TextField(blank=True, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
            },
        ),
        migrations.CreateModel(
            name='Cdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vigencia', models.IntegerField(choices=siifweb.models.listado_vigencias)),
                ('nro_cdp', models.CharField(max_length=20, verbose_name='Numero')),
                ('fecha_disp', models.DateField(verbose_name='Fecha expedicion CDP')),
                ('objeto_cert', models.TextField(blank=True, verbose_name='Objeto')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdps', to='siifweb.centrocosto', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vigencia', models.IntegerField(choices=siifweb.models.listado_vigencias)),
                ('nro_rp', models.CharField(max_length=20, verbose_name='Numero')),
                ('fecha_reg', models.DateField(verbose_name='Fecha expedicion RP')),
                ('acto_admon', models.TextField(blank=True, verbose_name='Acto administrativo')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='siifweb.centrocosto', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(max_length=250, verbose_name='Tipo de contrato')),
                ('nro_contrato', models.CharField(max_length=250, verbose_name='Numero de contrato')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de firma')),
                ('interventor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Interventor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='siifweb.centrocosto', verbose_name='Dependencia')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='siifweb.cargareporte')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='siifweb.tercero', verbose_name='Contratista')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='ContratoActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nro_orden', models.CharField(blank=True, max_length=20, verbose_name='Numero de orden')),
                ('tipo_orden', models.CharField(blank=True, max_length=250, verbose_name='Tipo de orden')),
                ('concepto', models.TextField(blank=True, verbose_name='Concepto')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('nrodoc_acta', models.CharField(blank=True, max_length=20, verbose_name='Numero de documento acta')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_del_contrato', to='siifweb.contrato', verbose_name='Contrato')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actas', to='siifweb.cargareporte')),
            ],
            options={
                'verbose_name': 'Acta del contrato',
                'verbose_name_plural': 'Actas del contrato',
            },
        ),
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vigencia', models.IntegerField(choices=siifweb.models.listado_vigencias)),
                ('nro_obligacion', models.CharField(max_length=20, verbose_name='Numero')),
                ('fecha_obli', models.DateField(verbose_name='Fecha obligacion')),
                ('nro_orden_gasto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de contrato asociado')),
                ('prefijo_orden', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vigencia del contrato')),
                ('orden_pago', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de orden de pago')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='siifweb.centrocosto', verbose_name='Dependencia')),
                ('tipo_orden_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='siifweb.ordengasto', verbose_name='Tipo de orden de gasto')),
            ],
            options={
                'verbose_name': 'Obligacion',
                'verbose_name_plural': 'Obligaciones',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bpin', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Codigo')),
                ('nombre', models.TextField(blank=True, null=True, verbose_name='Nombre')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='siifweb.centrocosto', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ReservaImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valor_reserva', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor reserva')),
                ('valor_reserva_def', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor reserva definitiva')),
                ('obligaciones_reserva', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Obligaciones reserva')),
                ('pagos_reserva', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pagos reserva')),
                ('saldo_reserva', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo reserva')),
                ('cdp_origen', models.ForeignKey(blank=True, help_text='CDP de la vigencia anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_imputadas', to='siifweb.cdp', verbose_name='CDP de origen')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_imputadas', to='siifweb.fuente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_imputadas', to='siifweb.proyecto')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_imputadas', to='siifweb.cargareporte')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_imputadas', to='siifweb.reserva', verbose_name='Reserva')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_imputadas', to='siifweb.rubro')),
            ],
            options={
                'verbose_name': 'Reserva imputada',
                'verbose_name_plural': 'Reservas imputadas',
            },
        ),
        migrations.CreateModel(
            name='ObligacionImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valor_obligacion', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor obligacion')),
                ('saldo_obli', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo obligacion')),
                ('pagos', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pagos')),
                ('saldo_obli_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado para comprobar el de SIIFWEB', max_digits=20, null=True, verbose_name='Saldo obligacion calculado')),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_imputadas', to='siifweb.compromiso')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_imputadas', to='siifweb.fuente')),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_imputadas', to='siifweb.obligacion')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_imputadas', to='siifweb.cargareporte')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_imputadas', to='siifweb.proyecto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_imputadas', to='siifweb.rubro')),
            ],
            options={
                'verbose_name': 'Imputacion de la obligacion',
                'verbose_name_plural': 'Imputacion de las obligaciones',
            },
        ),
        migrations.CreateModel(
            name='ContratoImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vigencia', models.IntegerField(blank=True, choices=siifweb.models.listado_vigencias, null=True, verbose_name='Vigencia')),
                ('nro_comprobante', models.CharField(blank=True, help_text='Ancla a la bitacora', max_length=20, verbose_name='Comprobante presupuestal')),
                ('compromiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_del_contrato', to='siifweb.compromiso', verbose_name='Compromiso (RP)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_del_contrato', to='siifweb.contrato', verbose_name='Contrato')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_del_contrato', to='siifweb.cargareporte')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_del_contrato', to='siifweb.fuente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_del_contrato', to='siifweb.proyecto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_del_contrato', to='siifweb.rubro')),
            ],
            options={
                'verbose_name': 'Imputacion del contrato',
                'verbose_name_plural': 'Imputaciones del contrato',
            },
        ),
        migrations.CreateModel(
            name='CompromisoImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valor_registro', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor registro')),
                ('valor_compromiso_def', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor compromiso definitivo')),
                ('saldo_rp', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo compromiso')),
                ('saldo_rp_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado desde la relacion para comprobar el de SIIFWEB', max_digits=20, null=True, verbose_name='Saldo compromiso calculado')),
                ('cdp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_imputados', to='siifweb.cdp')),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_imputados', to='siifweb.compromiso')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_imputados', to='siifweb.cargareporte')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_imputados', to='siifweb.fuente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_imputados', to='siifweb.proyecto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos_imputados', to='siifweb.rubro')),
            ],
            options={
                'verbose_name': 'Imputacion del compromiso',
                'verbose_name_plural': 'Imputacion de los compromisos',
            },
        ),
        migrations.CreateModel(
            name='CdpImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valor_certificado', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor certificado')),
                ('valor_disponibilidad_def', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor disponibilidad definitiva')),
                ('saldo_certf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Saldo certificado')),
                ('saldo_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado desde la relacion para comprobar el de SIIFWEB', max_digits=20, null=True, verbose_name='Saldo calculado')),
                ('cdp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdps_imputados', to='siifweb.cdp')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdps_imputados', to='siifweb.cargareporte')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdps_imputados', to='siifweb.fuente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdps_imputados', to='siifweb.proyecto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdps_imputados', to='siifweb.rubro')),
            ],
            options={
                'verbose_name': 'Imputacion del CDP',
                'verbose_name_plural': 'Imputacion de los CDPs',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='siifweb.tercero'),
        ),
        migrations.AddConstraint(
            model_name='cdp',
            constraint=models.UniqueConstraint(fields=('vigencia', 'nro_cdp'), name='cdp_unico_por_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='compromiso',
            constraint=models.UniqueConstraint(fields=('vigencia', 'nro_rp'), name='rp_unico_por_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='obligacion',
            constraint=models.UniqueConstraint(fields=('vigencia', 'nro_obligacion'), name='obligacion_unica_por_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('vigencia', 'nro_reserva'), name='reserva_unica_por_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(fields=('tipo_contrato', 'nro_contrato', 'fecha_firma', 'tercero'), name='contrato_unico'),
        ),
    ]
