# Generated by Django 6.0.7 on 2026-07-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='clasificacion',
            field=models.CharField(blank=True, help_text='POAI, regalias, vigencias futuras, recursos del balance...', max_length=120, null=True, verbose_name='Clasificacion (POAI)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='dependencia_responsable',
            field=models.CharField(blank=True, help_text='Del cruce POAI; puede diferir de la de SIIFWEB', max_length=120, null=True, verbose_name='Dependencia responsable (POAI)'),
        ),
        migrations.AlterField(
            model_name='cargareporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('cdp', 'Consolidado de disponibilidades'), ('compromisos', 'Consolidado de compromisos'), ('obligaciones', 'Consolidado de obligaciones'), ('reservas', 'Consolidado de reservas'), ('historial', 'Historial de orden de gasto 2 (rango completo)'), ('poai', 'Cruce proyectos POAI (opcional: nombre, dependencia y clasificacion)')], max_length=20, verbose_name='Tipo de reporte'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='dependencia',
            field=models.ForeignKey(blank=True, help_text='Centro de costo que ejecuta, segun SIIFWEB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='siifweb.centrocosto', verbose_name='Dependencia (SIIFWEB)'),
        ),
    ]
