# Generated by Django 6.0.7 on 2026-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0002_proyecto_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='origen',
            field=models.CharField(choices=[('manual', 'Ingresado por el equipo'), ('siifweb', 'Detectado en un reporte de SIIFWEB'), ('poai', 'Cruce POAI')], default='manual', help_text='Como entro el proyecto al sistema', max_length=10, verbose_name='Origen del registro'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='bpin',
            field=models.CharField(blank=True, help_text='BPIN. Se normaliza al guardar: sin espacios ni sufijo .0', max_length=25, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
