# Generated by Django 6.0.7 on 2026-07-20 21:13

import django.db.models.deletion
from django.db import migrations, models


def dimensionar(apps, schema_editor):
    """Pasa el texto que hoy vive en Proyecto a las dos tablas de dimension.

    La dependencia responsable NO se parte por coma: varios nombres las llevan
    dentro ("Mujer, Juventud, e Inclusion Social"). La clasificacion si, porque
    en el POAI llegan varias en una sola celda.

    Truco para la FK: el id que resulta se escribe de vuelta en la misma columna
    de texto, que en el paso siguiente se convierte en dependencia_responsable_id.
    """
    Clasificacion = apps.get_model("siifweb", "Clasificacion")
    DependenciaResponsable = apps.get_model("siifweb", "DependenciaResponsable")
    cursor = schema_editor.connection.cursor()
    cursor.execute("SELECT id, dependencia_responsable, clasificacion FROM siifweb_proyecto")
    filas = cursor.fetchall()

    deps, clases, m2m = {}, {}, []
    for pk, dep, clas in filas:
        dep = (dep or "").strip()
        if dep:
            if dep not in deps:
                deps[dep] = DependenciaResponsable.objects.create(nombre=dep[:150]).pk
            cursor.execute("UPDATE siifweb_proyecto SET dependencia_responsable = %s WHERE id = %s",
                           [str(deps[dep]), pk])
        else:
            cursor.execute("UPDATE siifweb_proyecto SET dependencia_responsable = NULL WHERE id = %s",
                           [pk])
        for parte in (clas or "").split(","):
            nombre = parte.strip()
            if not nombre:
                continue
            if nombre not in clases:
                clases[nombre] = Clasificacion.objects.create(nombre=nombre[:120]).pk
            m2m.append((pk, clases[nombre]))

    if m2m:
        cursor.executemany(
            "INSERT OR IGNORE INTO siifweb_proyecto_clasificaciones "
            "(proyecto_id, clasificacion_id) VALUES (%s, %s)", m2m)


def desdimensionar(apps, schema_editor):
    """Vuelta atras: deja los ids en NULL para que la columna de texto no quede con basura."""
    schema_editor.connection.cursor().execute(
        "UPDATE siifweb_proyecto SET dependencia_responsable = NULL, clasificacion = ''")


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0003_proyecto_origen_alter_proyecto_bpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Clasificacion',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='DependenciaResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Dependencia responsable',
                'verbose_name_plural': 'Dependencias responsables',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='clasificaciones',
            field=models.ManyToManyField(blank=True, help_text='Un proyecto puede tener varias: POAI 2026 y Recursos del Balance, por ejemplo', related_name='proyectos', to='siifweb.clasificacion', verbose_name='Clasificaciones (POAI)'),
        ),
        migrations.RunPython(dimensionar, desdimensionar),
        migrations.RemoveField(
            model_name='proyecto',
            name='clasificacion',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='dependencia_responsable',
            field=models.ForeignKey(blank=True, help_text='Quien responde por el proyecto; puede diferir de la que ejecuta en SIIFWEB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='siifweb.dependenciaresponsable', verbose_name='Dependencia responsable (POAI)'),
        ),
    ]
