# Generated by Django 6.0.7 on 2026-08-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0004_clasificacion_dependenciaresponsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='objeto_reg',
            field=models.TextField(blank=True, verbose_name='Objeto del registro'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='bpin',
            field=models.CharField(blank=True, help_text='BPIN. Se normaliza al guardar: sin espacios ni sufijo .0', max_length=25, null=True, unique=True, verbose_name='BPIN'),
        ),
    ]
