# Generated by Django 6.0.7 on 2026-08-28 01:21

import django.db.models.deletion
import siifweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0005_compromiso_objeto_reg_alter_proyecto_bpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargareporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('cdp', 'Consolidado de disponibilidades'), ('compromisos', 'Consolidado de compromisos'), ('obligaciones', 'Consolidado de obligaciones'), ('reservas', 'Consolidado de reservas'), ('historial', 'Historial de orden de gasto 2 (rango completo)'), ('poai', 'Cruce proyectos POAI (opcional: nombre, dependencia y clasificacion)'), ('secop', 'Consolidado BPIN por proceso de SECOP II (rango completo)')], max_length=20, verbose_name='Tipo de reporte'),
        ),
        migrations.AlterField(
            model_name='cargareporte',
            name='vigencia',
            field=models.IntegerField(blank=True, choices=siifweb.models.listado_vigencias, help_text='Dejar vacia en el historial de ordenes de gasto 2 y en el consolidado de SECOP II: se descargan por rango completo, no por vigencia', null=True, verbose_name='Vigencia'),
        ),
        migrations.CreateModel(
            name='ProcesoSecop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_proceso', models.CharField(max_length=60, unique=True, verbose_name='ID del proceso')),
                ('id_portafolio', models.CharField(blank=True, db_index=True, help_text='Agrupa procesos: 114 portafolios traen dos o tres', max_length=60, verbose_name='ID del portafolio')),
                ('estado_procedimiento', models.CharField(blank=True, max_length=60, verbose_name='Estado del procedimiento')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de publicacion')),
                ('fecha_ultima_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de ultima publicacion')),
                ('fecha_recepcion_respuestas', models.DateField(blank=True, null=True, verbose_name='Fecha de recepcion de respuestas')),
                ('fecha_apertura_respuestas', models.DateField(blank=True, null=True, verbose_name='Fecha de apertura de respuestas')),
                ('fecha_apertura_efectiva', models.DateField(blank=True, null=True, verbose_name='Fecha de apertura efectiva')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_secop', to='siifweb.cargareporte')),
            ],
            options={
                'verbose_name': 'Proceso de SECOP II',
                'verbose_name_plural': 'Procesos de SECOP II',
            },
        ),
        migrations.CreateModel(
            name='ContratoSecop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_contrato', models.CharField(max_length=60, unique=True, verbose_name='ID del contrato')),
                ('referencia', models.CharField(blank=True, help_text='Numeracion de SECOP (CPS-872-2024); no es el numero de contrato de SIIFWEB', max_length=120, verbose_name='Referencia del contrato')),
                ('estado', models.CharField(blank=True, max_length=60, verbose_name='Estado del contrato')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto del contrato')),
                ('descripcion_proceso', models.TextField(blank=True, verbose_name='Descripcion del proceso')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor del contrato')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de firma')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('url_proceso', models.TextField(blank=True, verbose_name='URL del proceso')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_secop', to='siifweb.tercero', verbose_name='Proveedor')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_secop', to='siifweb.cargareporte')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_del_proceso', to='siifweb.procesosecop', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Contrato de SECOP II',
                'verbose_name_plural': 'Contratos de SECOP II',
            },
        ),
        migrations.CreateModel(
            name='BpinProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bpin', models.CharField(db_index=True, max_length=25, verbose_name='BPIN')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Anio del BPIN')),
                ('validacion_bpin', models.CharField(blank=True, max_length=20, verbose_name='Validacion del BPIN')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Nulo si el BPIN no esta en el catalogo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_secop', to='siifweb.proyecto', verbose_name='Proyecto')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bpines_por_proceso', to='siifweb.cargareporte')),
                ('contrato_secop', models.ForeignKey(blank=True, help_text='Nulo si el proceso no tiene contrato adjudicado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bpines', to='siifweb.contratosecop', verbose_name='Contrato')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpines', to='siifweb.procesosecop', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'BPIN por proceso',
                'verbose_name_plural': 'BPIN por proceso',
                'constraints': [models.UniqueConstraint(fields=('bpin', 'proceso', 'contrato_secop'), name='bpin_proceso_unico')],
            },
        ),
    ]
