# Generated by Django 6.0.7 on 2026-08-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0006_alter_cargareporte_tipo_reporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligacion',
            name='objeto_oblig',
            field=models.TextField(blank=True, help_text='Columna OBJETO_OBLIG del consolidado', verbose_name='Objeto de la obligacion'),
        ),
    ]
