# Generated by Django 6.0.7 on 2026-08-28 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0007_obligacion_objeto_oblig'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligacion',
            name='beneficiario',
            field=models.ForeignKey(blank=True, help_text='Columnas NIT y BENEFICIARIO del consolidado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='siifweb.tercero', verbose_name='Beneficiario'),
        ),
    ]
