# Generated by Django 6.0.7 on 2026-08-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siifweb', '0009_roles_seguimiento_y_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='bpin',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='BPIN'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='clasificaciones',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='siifweb.clasificacion', verbose_name='Clasificaciones (POAI)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='siifweb.centrocosto', verbose_name='Dependencia (SIIFWEB)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='dependencia_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='siifweb.dependenciaresponsable', verbose_name='Dependencia responsable (POAI)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='origen',
            field=models.CharField(choices=[('manual', 'Ingresado por el equipo'), ('siifweb', 'Detectado en un reporte de SIIFWEB'), ('poai', 'Cruce POAI')], default='manual', max_length=10, verbose_name='Origen del registro'),
        ),
    ]
