"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import tempfile
from dotenv import load_dotenv
load_dotenv()
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").strip().lower() == "true"

# Railway inyecta RAILWAY_PUBLIC_DOMAIN por si solo: el dominio entra dinamico,
# sin configurar hosts ni CSRF a mano. EXTRA_* (coma-separados) abre la puerta a
# dominios propios o a ngrok en local.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]
CSRF_TRUSTED_ORIGINS = []

_railway_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN")
if _railway_domain:
    ALLOWED_HOSTS.append(_railway_domain)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_railway_domain}")

# Comodin para cualquier subdominio de Railway: RAILWAY_PUBLIC_DOMAIN no siempre
# se inyecta. El punto inicial en ALLOWED_HOSTS matchea todos los subdominios;
# CSRF (Django 4+) acepta el * en el origen.
ALLOWED_HOSTS.append(".up.railway.app")
CSRF_TRUSTED_ORIGINS.append("https://*.up.railway.app")

ALLOWED_HOSTS += [h.strip() for h in os.getenv("EXTRA_ALLOWED_HOSTS", "").split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS += [o.strip() for o in os.getenv("EXTRA_CSRF_ORIGINS", "").split(",") if o.strip()]

# Railway termina el TLS en su proxy: Django reconoce HTTPS por la cabecera reenviada.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
if not DEBUG:
    # En produccion todo por HTTPS (Railway ya sirve TLS; con el proxy header
    # de arriba, Django reconoce la conexion segura y redirige el resto).
    SECURE_SSL_REDIRECT = True
    # HSTS: opcional. Actívalo (p. ej. 31536000) cuando tengas un dominio estable;
    # es dificil de revertir, por eso arranca apagado.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))


# Application definition

INSTALLED_APPS = [
    # unfold va antes de django.contrib.admin: reemplaza sus plantillas
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'siifweb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise justo despues de SecurityMiddleware: sirve los estaticos
    # comprimidos y versionados sin depender de un servidor de archivos aparte.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AWS_ACCESS_KEY_ID = os.getenv("SUPABASE_S3_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SUPABASE_S3_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = "media"


AWS_S3_ENDPOINT_URL = "https://bhfkybfkgxerzvpatdkg.storage.supabase.co/storage/v1/s3"
AWS_S3_REGION_NAME = "us-east-1"

# Supabase exige path-style + firma v4
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_SIGNATURE_VERSION = "s3v4"

# Bucket privado -> URLs firmadas (default). No lo pongas en False para docs sensibles.
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 3600  # segundos de validez del link firmado

# Evita que dos archivos con el mismo nombre se sobreescriban silenciosamente
AWS_S3_FILE_OVERWRITE = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            # Sin prefijo: el modelo ya sube con upload_to="reportes/". El bucket
            # se llama "media", asi que los archivos quedan en media/reportes/...
            "location": "",
        },
    },
    "staticfiles": {
        # WhiteNoise: comprime y versiona los estáticos (cache-busting).
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        ),
    }
else:
    DATABASES = {
        'default' : {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME' : BASE_DIR / 'db.sqlite3'
        }
    }

# Las pruebas NUNCA tocan produccion. El .env trae DATABASE_URL apuntando a Supabase
# y el almacenamiento por defecto es el bucket S3, asi que sin esta guarda un
# `manage.py test` crearia una base de prueba alla y subiria los archivos al bucket.
# Con ella, las pruebas corren siempre en sqlite en memoria y en disco temporal.
if sys.argv[1:2] == ["test"]:
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        # El manifiesto de WhiteNoise exige un collectstatic previo: en pruebas estorba
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
    MEDIA_ROOT = Path(tempfile.mkdtemp(prefix="siifweb-pruebas-"))
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CSRF_TRUSTED_ORIGINS se arma arriba desde RAILWAY_PUBLIC_DOMAIN + EXTRA_CSRF_ORIGINS.
# Para ngrok en local: EXTRA_CSRF_ORIGINS=https://tu-dominio.ngrok-free.dev en el .env


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Archivos subidos (los xlsx de los reportes)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Los reportes grandes traen decenas de miles de filas en un solo POST del admin
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024


# ---------------------------------------------------------------------------
# django-unfold: apariencia del admin
# ---------------------------------------------------------------------------

def _static_versionado(ruta):
    """Cuelga ?v=<mtime> a un estatico para reventar la cache del navegador.

    Sin esto, cada cambio en el CSS obliga a un Ctrl+F5 en cada maquina del
    equipo: el navegador reusa la version vieja. Al ligar la version a la fecha
    de modificacion del archivo, cada edicion cambia la URL y se vuelve a bajar.
    """
    archivo = BASE_DIR / "static" / ruta
    version = int(archivo.stat().st_mtime) if archivo.exists() else 0
    return lambda request: f"{static(ruta)}?v={version}"

def _con_permiso(*permisos):
    """Oculta un enlace del menu lateral a quien no puede abrirlo.

    Sin esto, un rol acotado -Seguimiento o Consulta- veria en la barra lateral
    paginas que le contestan 403. Unfold llama al callback con el request; el
    superusuario pasa siempre, porque has_perm le devuelve True a todo. Si todos
    los enlaces de una seccion se ocultan, la seccion entera desaparece.
    """
    return lambda request: any(request.user.has_perm(p) for p in permisos)


def _administra_los_datos(request):
    """Deja ver las secciones del menu que listan lo que producen las cargas.

    Los roles Seguimiento y Consulta tienen habilitado un solo modulo, el de
    Seguimiento: revisan la ejecucion en la ficha del proyecto y no en las tablas
    documento por documento. La llave es el permiso sobre las cargas del reporte
    -quien sube los archivos es quien mantiene esas tablas-, asi que sigue siendo un
    permiso y no un chequeo de superusuario.
    """
    return request.user.has_perm("siifweb.view_cargareporte")


UNFOLD = {
    "SITE_TITLE": "POAI",
    "SITE_HEADER": "POAI",
    "SITE_SUBHEADER": "Integración POAI - SIIFWEB",
    "SITE_URL" : "/",
    "SHOW_VIEW_ON_SITE": False,
    "SITE_SYMBOL": "account_balance",
    "SHOW_HISTORY": True,
    "THEME": "light",
    "SHOW_BACK_BUTTON": False,
    "STYLES": [
        _static_versionado("css/admin_styles.css"),
    ],
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "base": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "209 213 219",
            "400": "156 163 175",
            "500": "107 114 128",
            "600": "75 85 99",
            "700": "55 65 81",
            "800": "31 41 55",
            "900": "17 24 39",
            "950": "3 7 18",
        },
        "primary": {
            "50": "240 249 243",    # Verde muy claro
            "100": "220 242 226",   # Verde claro
            "200": "188 230 201",   # Verde suave
            "300": "146 212 168",   # Verde medio suave
            "400": "109 213 124",   # Verde medio
            "500": "16 157 57",     # Verde original (#109D39)
            "600": "15 142 52",     # Verde ligeramente oscuro
            "700": "13 122 44",     # Verde oscuro
            "800": "11 102 37",     # Verde muy oscuro
            "900": "9 82 29",       # Verde extremadamente oscuro
            "950": "5 46 16",       # Verde casi negro
        },
        "font": {
            "subtle-light": "var(--color-base-500)",     # Gris medio para texto sutil
            "subtle-dark": "var(--color-base-400)",      # Gris claro para texto sutil en modo oscuro
            "default-light": "var(--color-base-700)",    # Gris oscuro para texto normal
            "default-dark": "var(--color-base-200)",     # Gris muy claro para texto normal en modo oscuro
            "important-light": "var(--color-base-900)",  # Negro muy oscuro para texto importante
            "important-dark": "var(--color-base-100)",   # Blanco casi puro para texto importante en modo oscuro
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title" : "Usuarios",
                "separator" : False,
                "items": [
                    {"title":"Roles","icon":"groups","link":reverse_lazy("admin:auth_group_changelist"),
                     "permission": _con_permiso("auth.view_group")},
                    {"title":"Usuarios","icon":"user_attributes","link":reverse_lazy("admin:auth_user_changelist"),
                     "permission": _con_permiso("auth.view_user")}
                ]
            },
            {
                "title": "Seguimiento",
                "separator": True,
                "items": [
                    {"title": "Proyectos", "icon": "folder_special",
                     "link": reverse_lazy("admin:siifweb_proyecto_changelist"),
                     "permission": _con_permiso("siifweb.view_proyecto")},
                    {"title": "Dashboard", "icon": "monitoring",
                     "link": reverse_lazy("admin:siifweb_proyecto_tablero"),
                     "permission": _con_permiso("siifweb.view_proyecto")},
                    {"title": "Reportes", "icon": "table_view",
                     "link": reverse_lazy("admin:siifweb_proyecto_reporte_financiero"),
                     "permission": _con_permiso("siifweb.view_proyecto")},
                ],
            },
            {
                "title": "Configruación y parametrización",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Terceros", "icon": "groups",
                     "link": reverse_lazy("admin:siifweb_tercero_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Rubros", "icon": "list_alt",
                     "link": reverse_lazy("admin:siifweb_rubro_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Fuentes", "icon": "account_tree",
                     "link": reverse_lazy("admin:siifweb_fuente_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Dependencias", "icon": "corporate_fare",
                     "link": reverse_lazy("admin:siifweb_centrocosto_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Dependencias responsables", "icon": "badge",
                     "link": reverse_lazy("admin:siifweb_dependenciaresponsable_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Clasificaciones", "icon": "sell",
                     "link": reverse_lazy("admin:siifweb_clasificacion_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Cargas del reporte", "icon": "upload_file",
                     "link": reverse_lazy("admin:siifweb_cargareporte_changelist"),
                     "permission": _administra_los_datos},
                ],
            },
            {
                "title": "Cadena de gasto",
                "collapsible":True,
                "separator": True,
                "items": [
                    {"title": "Disponibilidades (CDP)", "icon": "request_quote",
                     "link": reverse_lazy("admin:siifweb_cdp_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Compromisos (RP)", "icon": "handshake",
                     "link": reverse_lazy("admin:siifweb_compromiso_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Obligaciones", "icon": "receipt_long",
                     "link": reverse_lazy("admin:siifweb_obligacion_changelist"),
                     "permission": _administra_los_datos},
                ],
            },
            {
                "title": "Cierre de vigencia",
                "collapsible":True,
                "separator": True,
                "items": [
                    {"title": "Reservas", "icon": "event_repeat",
                     "link": reverse_lazy("admin:siifweb_reserva_changelist"),
                     "permission": _administra_los_datos},
                ],
            },
            {
                "title": "Contratación",
                "collapsible" :True,
                "separator": True,
                "items": [
                    {"title": "Contratos", "icon": "contract",
                     "link": reverse_lazy("admin:siifweb_contrato_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Actas de pago", "icon": "payments",
                     "link": reverse_lazy("admin:siifweb_contratoacta_changelist"),
                     "permission": _administra_los_datos},
                ],
            },
            {
                "title": "Contratación pública (SECOP II)",
                "collapsible": True,
                "separator": True,
                "items": [
                    {"title": "Contratos de SECOP II", "icon": "gavel",
                     "link": reverse_lazy("admin:siifweb_contratosecop_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "Procesos de SECOP II", "icon": "how_to_vote",
                     "link": reverse_lazy("admin:siifweb_procesosecop_changelist"),
                     "permission": _administra_los_datos},
                    {"title": "BPIN por proceso", "icon": "account_tree",
                     "link": reverse_lazy("admin:siifweb_bpinproceso_changelist"),
                     "permission": _administra_los_datos},
                ],
            },
        ],
    },
}
